// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220804084132_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Data.Model.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"), 1L, 1);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorName = "Robert De Niro"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorName = "Jack Nicholson"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorName = "Marlon Brando"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorName = "Denzel Washington"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorName = "Katharine Hepburn"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorName = "Humphrey Bogart"
                        },
                        new
                        {
                            ActorId = 7,
                            ActorName = "Meryl Streep"
                        },
                        new
                        {
                            ActorId = 8,
                            ActorName = "Daniel Day-Lewis"
                        },
                        new
                        {
                            ActorId = 9,
                            ActorName = "Sidney Poitier"
                        },
                        new
                        {
                            ActorId = 10,
                            ActorName = "Clark Gable"
                        },
                        new
                        {
                            ActorId = 11,
                            ActorName = "Ingrid Bergman"
                        },
                        new
                        {
                            ActorId = 12,
                            ActorName = "Tom Hanks"
                        },
                        new
                        {
                            ActorId = 13,
                            ActorName = "Elizabeth Taylor"
                        },
                        new
                        {
                            ActorId = 14,
                            ActorName = "Bette Davis"
                        },
                        new
                        {
                            ActorId = 15,
                            ActorName = "Gregory Peck"
                        },
                        new
                        {
                            ActorId = 16,
                            ActorName = "Leonardo DiCaprio"
                        },
                        new
                        {
                            ActorId = 17,
                            ActorName = "Cate Blanchett"
                        },
                        new
                        {
                            ActorId = 18,
                            ActorName = "Audrey Hepburn"
                        },
                        new
                        {
                            ActorId = 19,
                            ActorName = "Spencer Tracy"
                        },
                        new
                        {
                            ActorId = 20,
                            ActorName = "Kate Winslet"
                        });
                });

            modelBuilder.Entity("Api.Data.Model.ActorEpisode", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("ActorEpisode", (string)null);

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 1
                        },
                        new
                        {
                            ActorId = 6,
                            EpisodeId = 2
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 2
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 2
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 2
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 2
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 3
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 3
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 3
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 3
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 3
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 4
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 4
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 4
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 4
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 4
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 5
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 5
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 5
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 5
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 5
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 6
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 6
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 6
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 6
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 6
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 7
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 7
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 7
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 7
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 7
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 8
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 8
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 8
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 8
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 9
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 9
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 9
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 9
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 9
                        },
                        new
                        {
                            ActorId = 6,
                            EpisodeId = 10
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 10
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 10
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 10
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 10
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 11
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 11
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 11
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 11
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 11
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 12
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 12
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 12
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 12
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 12
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 13
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 13
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 13
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 13
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 13
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 14
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 14
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 14
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 14
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 14
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 15
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 15
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 15
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 15
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 15
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 16
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 16
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 16
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 16
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 21
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 21
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 21
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 21
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 21
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 22
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 22
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 22
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 22
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 22
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 23
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 23
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 23
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 23
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 23
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 24
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 24
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 24
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 24
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 24
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 25
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 25
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 25
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 25
                        },
                        new
                        {
                            ActorId = 6,
                            EpisodeId = 25
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 26
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 26
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 26
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 26
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 27
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 27
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 27
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 27
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 27
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 28
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 28
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 28
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 28
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 28
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 29
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 29
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 29
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 29
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 29
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 30
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 30
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 30
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 31
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 31
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 32
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 32
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 32
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 32
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 32
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 33
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 33
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 33
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 33
                        },
                        new
                        {
                            ActorId = 1,
                            EpisodeId = 34
                        },
                        new
                        {
                            ActorId = 2,
                            EpisodeId = 34
                        },
                        new
                        {
                            ActorId = 3,
                            EpisodeId = 34
                        },
                        new
                        {
                            ActorId = 4,
                            EpisodeId = 34
                        },
                        new
                        {
                            ActorId = 5,
                            EpisodeId = 34
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 35
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 35
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 35
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 35
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 35
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 36
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 36
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 36
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 36
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 36
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 37
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 37
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 37
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 37
                        },
                        new
                        {
                            ActorId = 7,
                            EpisodeId = 38
                        },
                        new
                        {
                            ActorId = 8,
                            EpisodeId = 38
                        },
                        new
                        {
                            ActorId = 9,
                            EpisodeId = 38
                        },
                        new
                        {
                            ActorId = 10,
                            EpisodeId = 38
                        },
                        new
                        {
                            ActorId = 11,
                            EpisodeId = 38
                        },
                        new
                        {
                            ActorId = 12,
                            EpisodeId = 39
                        },
                        new
                        {
                            ActorId = 13,
                            EpisodeId = 39
                        },
                        new
                        {
                            ActorId = 14,
                            EpisodeId = 39
                        },
                        new
                        {
                            ActorId = 15,
                            EpisodeId = 39
                        },
                        new
                        {
                            ActorId = 16,
                            EpisodeId = 39
                        },
                        new
                        {
                            ActorId = 17,
                            EpisodeId = 40
                        },
                        new
                        {
                            ActorId = 18,
                            EpisodeId = 40
                        },
                        new
                        {
                            ActorId = 19,
                            EpisodeId = 40
                        },
                        new
                        {
                            ActorId = 20,
                            EpisodeId = 40
                        });
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.Credentials", b =>
                {
                    b.Property<int>("CredentialsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialsID"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialsID");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<int>("CredentialsID")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CredentialsID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Data.Model.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EpisodeId"), 1L, 1);

                    b.Property<string>("EpisodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            EpisodeName = "volume",
                            EpisodeNumber = 1,
                            SeasonId = 1
                        },
                        new
                        {
                            EpisodeId = 2,
                            EpisodeName = "association",
                            EpisodeNumber = 2,
                            SeasonId = 1
                        },
                        new
                        {
                            EpisodeId = 3,
                            EpisodeName = "promotion",
                            EpisodeNumber = 1,
                            SeasonId = 2
                        },
                        new
                        {
                            EpisodeId = 4,
                            EpisodeName = "interaction",
                            EpisodeNumber = 2,
                            SeasonId = 2
                        },
                        new
                        {
                            EpisodeId = 5,
                            EpisodeName = "camera",
                            EpisodeNumber = 1,
                            SeasonId = 3
                        },
                        new
                        {
                            EpisodeId = 6,
                            EpisodeName = "knowledge",
                            EpisodeNumber = 2,
                            SeasonId = 3
                        },
                        new
                        {
                            EpisodeId = 7,
                            EpisodeName = "cookie",
                            EpisodeNumber = 1,
                            SeasonId = 4
                        },
                        new
                        {
                            EpisodeId = 8,
                            EpisodeName = "employer",
                            EpisodeNumber = 2,
                            SeasonId = 4
                        },
                        new
                        {
                            EpisodeId = 9,
                            EpisodeName = "revenue",
                            EpisodeNumber = 1,
                            SeasonId = 5
                        },
                        new
                        {
                            EpisodeId = 10,
                            EpisodeName = "selection",
                            EpisodeNumber = 2,
                            SeasonId = 5
                        },
                        new
                        {
                            EpisodeId = 11,
                            EpisodeName = "piano",
                            EpisodeNumber = 1,
                            SeasonId = 6
                        },
                        new
                        {
                            EpisodeId = 12,
                            EpisodeName = "airport",
                            EpisodeNumber = 2,
                            SeasonId = 6
                        },
                        new
                        {
                            EpisodeId = 13,
                            EpisodeName = "news",
                            EpisodeNumber = 1,
                            SeasonId = 7
                        },
                        new
                        {
                            EpisodeId = 14,
                            EpisodeName = "friendship",
                            EpisodeNumber = 2,
                            SeasonId = 7
                        },
                        new
                        {
                            EpisodeId = 15,
                            EpisodeName = "intention",
                            EpisodeNumber = 1,
                            SeasonId = 8
                        },
                        new
                        {
                            EpisodeId = 16,
                            EpisodeName = "understanding",
                            EpisodeNumber = 2,
                            SeasonId = 8
                        },
                        new
                        {
                            EpisodeId = 21,
                            EpisodeName = "guitar",
                            EpisodeNumber = 1,
                            SeasonId = 11
                        },
                        new
                        {
                            EpisodeId = 22,
                            EpisodeName = "initiative",
                            EpisodeNumber = 2,
                            SeasonId = 11
                        },
                        new
                        {
                            EpisodeId = 23,
                            EpisodeName = "relationship",
                            EpisodeNumber = 1,
                            SeasonId = 12
                        },
                        new
                        {
                            EpisodeId = 24,
                            EpisodeName = "safety",
                            EpisodeNumber = 2,
                            SeasonId = 12
                        },
                        new
                        {
                            EpisodeId = 25,
                            EpisodeName = "data",
                            EpisodeNumber = 1,
                            SeasonId = 13
                        },
                        new
                        {
                            EpisodeId = 26,
                            EpisodeName = "ad",
                            EpisodeNumber = 2,
                            SeasonId = 13
                        },
                        new
                        {
                            EpisodeId = 27,
                            EpisodeName = "bath",
                            EpisodeNumber = 1,
                            SeasonId = 14
                        },
                        new
                        {
                            EpisodeId = 28,
                            EpisodeName = "platform",
                            EpisodeNumber = 2,
                            SeasonId = 14
                        },
                        new
                        {
                            EpisodeId = 29,
                            EpisodeName = "hall",
                            EpisodeNumber = 1,
                            SeasonId = 15
                        },
                        new
                        {
                            EpisodeId = 30,
                            EpisodeName = "quality",
                            EpisodeNumber = 2,
                            SeasonId = 15
                        },
                        new
                        {
                            EpisodeId = 31,
                            EpisodeName = "girlfriend",
                            EpisodeNumber = 1,
                            SeasonId = 16
                        },
                        new
                        {
                            EpisodeId = 32,
                            EpisodeName = "dirt",
                            EpisodeNumber = 2,
                            SeasonId = 16
                        },
                        new
                        {
                            EpisodeId = 33,
                            EpisodeName = "complaint",
                            EpisodeNumber = 1,
                            SeasonId = 17
                        },
                        new
                        {
                            EpisodeId = 34,
                            EpisodeName = "examination",
                            EpisodeNumber = 2,
                            SeasonId = 17
                        },
                        new
                        {
                            EpisodeId = 35,
                            EpisodeName = "assignment",
                            EpisodeNumber = 1,
                            SeasonId = 18
                        },
                        new
                        {
                            EpisodeId = 36,
                            EpisodeName = "chocolate",
                            EpisodeNumber = 2,
                            SeasonId = 18
                        },
                        new
                        {
                            EpisodeId = 37,
                            EpisodeName = "beer",
                            EpisodeNumber = 1,
                            SeasonId = 19
                        },
                        new
                        {
                            EpisodeId = 38,
                            EpisodeName = "passion",
                            EpisodeNumber = 2,
                            SeasonId = 19
                        },
                        new
                        {
                            EpisodeId = 39,
                            EpisodeName = "night",
                            EpisodeNumber = 1,
                            SeasonId = 20
                        },
                        new
                        {
                            EpisodeId = 40,
                            EpisodeName = "reception",
                            EpisodeNumber = 2,
                            SeasonId = 20
                        });
                });

            modelBuilder.Entity("Api.Data.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Musical"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Drama"
                        });
                });

            modelBuilder.Entity("Api.Data.Model.GenreSerie", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("SerieId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "SerieId");

                    b.HasIndex("SerieId");

                    b.ToTable("GenreSerie", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            SerieId = 1
                        },
                        new
                        {
                            GenreId = 1,
                            SerieId = 2
                        },
                        new
                        {
                            GenreId = 2,
                            SerieId = 3
                        },
                        new
                        {
                            GenreId = 2,
                            SerieId = 4
                        },
                        new
                        {
                            GenreId = 3,
                            SerieId = 6
                        },
                        new
                        {
                            GenreId = 3,
                            SerieId = 7
                        },
                        new
                        {
                            GenreId = 4,
                            SerieId = 8
                        },
                        new
                        {
                            GenreId = 4,
                            SerieId = 9
                        },
                        new
                        {
                            GenreId = 5,
                            SerieId = 10
                        });
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"), 1L, 1);

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SerieId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.HasIndex("SerieId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            SeasonNumber = 1,
                            SerieId = 1
                        },
                        new
                        {
                            SeasonId = 2,
                            SeasonNumber = 2,
                            SerieId = 1
                        },
                        new
                        {
                            SeasonId = 3,
                            SeasonNumber = 1,
                            SerieId = 2
                        },
                        new
                        {
                            SeasonId = 4,
                            SeasonNumber = 2,
                            SerieId = 2
                        },
                        new
                        {
                            SeasonId = 5,
                            SeasonNumber = 1,
                            SerieId = 3
                        },
                        new
                        {
                            SeasonId = 6,
                            SeasonNumber = 2,
                            SerieId = 3
                        },
                        new
                        {
                            SeasonId = 7,
                            SeasonNumber = 1,
                            SerieId = 4
                        },
                        new
                        {
                            SeasonId = 8,
                            SeasonNumber = 2,
                            SerieId = 4
                        },
                        new
                        {
                            SeasonId = 11,
                            SeasonNumber = 1,
                            SerieId = 6
                        },
                        new
                        {
                            SeasonId = 12,
                            SeasonNumber = 2,
                            SerieId = 6
                        },
                        new
                        {
                            SeasonId = 13,
                            SeasonNumber = 1,
                            SerieId = 7
                        },
                        new
                        {
                            SeasonId = 14,
                            SeasonNumber = 2,
                            SerieId = 7
                        },
                        new
                        {
                            SeasonId = 15,
                            SeasonNumber = 1,
                            SerieId = 8
                        },
                        new
                        {
                            SeasonId = 16,
                            SeasonNumber = 2,
                            SerieId = 8
                        },
                        new
                        {
                            SeasonId = 17,
                            SeasonNumber = 1,
                            SerieId = 9
                        },
                        new
                        {
                            SeasonId = 18,
                            SeasonNumber = 2,
                            SerieId = 9
                        },
                        new
                        {
                            SeasonId = 19,
                            SeasonNumber = 1,
                            SerieId = 10
                        },
                        new
                        {
                            SeasonId = 20,
                            SeasonNumber = 2,
                            SerieId = 10
                        });
                });

            modelBuilder.Entity("Api.Data.Model.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerieId"), 1L, 1);

                    b.Property<string>("SerieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerieId");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            SerieId = 1,
                            SerieName = "Planet Earth II"
                        },
                        new
                        {
                            SerieId = 2,
                            SerieName = "Breaking Bad"
                        },
                        new
                        {
                            SerieId = 3,
                            SerieName = "Planet Earth"
                        },
                        new
                        {
                            SerieId = 4,
                            SerieName = "Band of Brothers"
                        },
                        new
                        {
                            SerieId = 6,
                            SerieName = "The Wire"
                        },
                        new
                        {
                            SerieId = 7,
                            SerieName = "Blue Planet II"
                        },
                        new
                        {
                            SerieId = 8,
                            SerieName = "Avatar: The Last Airbender"
                        },
                        new
                        {
                            SerieId = 9,
                            SerieName = "Cosmos: A Spacetime Odyssey"
                        },
                        new
                        {
                            SerieId = 10,
                            SerieName = "The Sopranos"
                        });
                });

            modelBuilder.Entity("Api.Data.Model.ActorEpisode", b =>
                {
                    b.HasOne("Api.Data.Model.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Model.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.User", b =>
                {
                    b.HasOne("Api.Data.Model.Authentication.Credentials", "Credentials")
                        .WithOne("User")
                        .HasForeignKey("Api.Data.Model.Authentication.User", "CredentialsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("Api.Data.Model.Episode", b =>
                {
                    b.HasOne("Api.Data.Model.Season", "EpisodeSeason")
                        .WithMany("SeasonEpisodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EpisodeSeason");
                });

            modelBuilder.Entity("Api.Data.Model.GenreSerie", b =>
                {
                    b.HasOne("Api.Data.Model.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Model.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.HasOne("Api.Data.Model.Serie", "SeasonSerie")
                        .WithMany("SerieSeasons")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SeasonSerie");
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.Credentials", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.Navigation("SeasonEpisodes");
                });

            modelBuilder.Entity("Api.Data.Model.Serie", b =>
                {
                    b.Navigation("SerieSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
