// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220802114102_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ActorEpisode", b =>
                {
                    b.Property<int>("ActorEpisodesEpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeActorsActorId")
                        .HasColumnType("int");

                    b.HasKey("ActorEpisodesEpisodeId", "EpisodeActorsActorId");

                    b.HasIndex("EpisodeActorsActorId");

                    b.ToTable("ActorEpisode");
                });

            modelBuilder.Entity("Api.Data.Model.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"), 1L, 1);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.Credentials", b =>
                {
                    b.Property<int>("CredentialsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialsID"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialsID");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<int>("CredentialsID")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CredentialsID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Data.Model.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EpisodeId"), 1L, 1);

                    b.Property<string>("EpisodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Api.Data.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"), 1L, 1);

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SerieId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.HasIndex("SerieId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Api.Data.Model.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerieId"), 1L, 1);

                    b.Property<string>("SerieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerieId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("GenreSerie", b =>
                {
                    b.Property<int>("GenreSerieSerieId")
                        .HasColumnType("int");

                    b.Property<int>("SerieGenresGenreId")
                        .HasColumnType("int");

                    b.HasKey("GenreSerieSerieId", "SerieGenresGenreId");

                    b.HasIndex("SerieGenresGenreId");

                    b.ToTable("GenreSerie");
                });

            modelBuilder.Entity("ActorEpisode", b =>
                {
                    b.HasOne("Api.Data.Model.Episode", null)
                        .WithMany()
                        .HasForeignKey("ActorEpisodesEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Model.Actor", null)
                        .WithMany()
                        .HasForeignKey("EpisodeActorsActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.User", b =>
                {
                    b.HasOne("Api.Data.Model.Authentication.Credentials", "Credentials")
                        .WithOne("User")
                        .HasForeignKey("Api.Data.Model.Authentication.User", "CredentialsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("Api.Data.Model.Episode", b =>
                {
                    b.HasOne("Api.Data.Model.Season", "EpisodeSeason")
                        .WithMany("SeasonEpisodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EpisodeSeason");
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.HasOne("Api.Data.Model.Serie", "SeasonSerie")
                        .WithMany("SerieSeasons")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SeasonSerie");
                });

            modelBuilder.Entity("GenreSerie", b =>
                {
                    b.HasOne("Api.Data.Model.Serie", null)
                        .WithMany()
                        .HasForeignKey("GenreSerieSerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Model.Genre", null)
                        .WithMany()
                        .HasForeignKey("SerieGenresGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Data.Model.Authentication.Credentials", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Data.Model.Season", b =>
                {
                    b.Navigation("SeasonEpisodes");
                });

            modelBuilder.Entity("Api.Data.Model.Serie", b =>
                {
                    b.Navigation("SerieSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
